import 'dart:ffi';

import 'package:TigerChat/pages/chat/logic/tb_chat_detail_logic.dart';
import 'package:TigerChat/util/common_tools.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:provider/provider.dart';

import '../../../constant/tb_export_common.dart';
import '../../../util/provider/chat_provider.dart';
import '../model/chat_response_model.dart';

class ChatLikeTool extends StatelessWidget {
  int indexNum;
  bool isUnlike;
  late ChatResponseModel? model;

  void Function() copyTap;
  void Function(bool) likeTap;
  void Function() shareTap;
  void Function() regenerateTap;
  void Function() reportTap;
  ChatLikeTool(
      {required this.indexNum,
      required this.isUnlike,
      required this.model,
      required this.likeTap,
      required this.shareTap,
      required this.copyTap,
      required this.reportTap,
      required this.regenerateTap});

  // Widget _item({isLike = true, onTap}) {
  //   final fillImageName = isLike
  //       ? "assets/images/chat/chat_like_fill.png"
  //       : "assets/images/chat/chat_unlike_fill.png";
  //
  //   final normalImageName = isLike
  //       ? "assets/images/chat/chat_like.png"
  //       : "assets/images/chat/chat_unlike.png";
  //
  //   final field = isLike ? this.isLike : this.isUnlike;
  //
  //   return GestureDetector(
  //     child: Container(
  //       width: 20.w,
  //       height: 20.w,
  //       padding: EdgeInsets.all(2.w),
  //       child: Image.asset(
  //         field ? fillImageName : normalImageName,
  //         width: 16.w,
  //       ),
  //     ),
  //     onTap: () {
  //       onTap(!field);
  //     },
  //   );
  // }

  Widget _pageItem(TBChatDetailLogic state,
      {VoidCallback? onLeftTap, VoidCallback? onNextTap}) {
    final total = model?.siblingMessageIds?.length ?? 0;
    final current = model?.currentPage ?? 1;

    return PageIndicator(
      current: current,
      total: total,
      onLeftTap: onLeftTap,
      onNextTap: onNextTap,
    );
  }

  @override
  Widget build(BuildContext context) {
    return GetBuilder<TBChatDetailLogic>(
        id: TBDefVal.kChatLikeTool,
        builder: (state) {
          return Padding(
            padding: EdgeInsets.only(left: 5.w),
            child: Column(
              children: [
                Align(
                  alignment: Alignment.centerLeft, // 设置文本左对齐
                  child: Text(
                    'The above content is generated by AI.'.tr,
                    style: TextStyle(
                      color: themed.theme_c.textColorMild,
                      fontSize: TBDefVal.chatTipsFont.sp,
                    ),
                  ),
                ),
                SizedBox(
                  height: 10.w,
                ),
                // Divider(
                //   height: 1,
                //   color: themed.theme_c.lineColor,
                // ),
                // SizedBox(
                //   height: 5.w,
                // ),
                Padding(
                  padding: EdgeInsets.only(top: 10.w),
                  child: Row(
                    // mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      if (((model?.siblingMessageIds?.length ?? 0) > 1))
                        _pageItem(
                          state,
                          onLeftTap: () {
                            ChatProvider chatProvider =
                                Provider.of<ChatProvider>(context,
                                    listen: false);
                            if (chatProvider.isStreamLoading) {
                              Fluttertoast.showToast(
                                  msg: 'Please wait'.tr,
                                  gravity: ToastGravity.CENTER);
                              return;
                            }
                            // 处理左侧按钮点击事件
                            model?.currentPage = (model?.currentPage ?? 1) - 1;
                            state.currentPage = model?.currentPage ?? 1;
                            state.dataSourceIndex = indexNum;
                            state.messagesId = model?.siblingMessageIds?[
                                    (model?.currentPage ?? 1) - 1] ??
                                '';
                            print('Left button tapped ${model?.currentPage}');
                            // state.update([TBDefVal.kChatLikeTool]);
                            state.requestMessage();
                          },
                          onNextTap: () {
                            ChatProvider chatProvider =
                                Provider.of<ChatProvider>(context,
                                    listen: false);
                            if (chatProvider.isStreamLoading) {
                              Fluttertoast.showToast(
                                  msg: 'Please wait'.tr,
                                  gravity: ToastGravity.CENTER);
                              return;
                            }
                            model?.currentPage = (model?.currentPage ?? 1) + 1;
                            state.currentPage = model?.currentPage ?? 1;
                            state.dataSourceIndex = indexNum;
                            state.messagesId = model?.siblingMessageIds?[
                                    (model?.currentPage ?? 1) - 1] ??
                                '';
                            // 处理右侧按钮点击事件
                            print('Right button tapped ${model?.currentPage}');
                            // state.update([TBDefVal.kChatLikeTool]);
                            state.requestMessage();
                          },
                        )
                      else
                        SizedBox(
                          width: 0.w,
                        ),
                      state.isLast
                          ? GestureDetector(
                              onTap: () {
                                ChatProvider chatProvider =
                                    Provider.of<ChatProvider>(context,
                                        listen: false);
                                if (chatProvider.isStreamLoading) {
                                  Fluttertoast.showToast(
                                      msg: 'Please wait'.tr,
                                      gravity: ToastGravity.CENTER);
                                  return;
                                }
                                this.regenerateTap();
                              },
                              child: Row(
                                children: [
                                  Image.asset(
                                    imagePath("chat", "chat_refresh"),
                                    width: 20.w,
                                    color:
                                        themed.theme_c.iconColorMild, // 你想要的颜色
                                    colorBlendMode: BlendMode.srcIn, // 混合模式
                                  ),
                                ],
                              ),
                            )
                          : SizedBox(
                              width: 0.w,
                            ),
                      state.isLast
                          ? SizedBox(
                              width: 10.w,
                            )
                          : SizedBox(
                              width: 0.w,
                            ),

                      GestureDetector(
                        child: Container(
                          width: 20.w,
                          height: 20.w,
                          padding: EdgeInsets.all(1.w),
                          child: Image.asset(
                            "assets/images/chat/chat_detail_edit.png",
                            width: 16.w,
                            color: themed.theme_c.iconColorMild, // 你想要的颜色
                            colorBlendMode: BlendMode.srcIn, // 混合模式
                          ),
                        ),
                        onTap: () {
                          ChatProvider chatProvider =
                              Provider.of<ChatProvider>(context, listen: false);
                          if (chatProvider.isStreamLoading) {
                            Fluttertoast.showToast(
                                msg: 'Please wait'.tr,
                                gravity: ToastGravity.CENTER);
                            return;
                          }
                          this.copyTap();
                        },
                      ),
                      // Spacer(),
                      SizedBox(
                        width: 10.w,
                      ),
                      GestureDetector(
                        child: Container(
                          width: 20.w,
                          height: 20.w,
                          padding: EdgeInsets.all(1.w),
                          child: Image.asset(
                            "assets/images/chat/chat_share_icon.png",
                            width: 16.w,
                            color: themed.theme_c.iconColorMild, // 你想要的颜色
                            colorBlendMode: BlendMode.srcIn, // 混合模式
                          ),
                        ),
                        onTap: () {
                          ChatProvider chatProvider =
                              Provider.of<ChatProvider>(context, listen: false);
                          if (chatProvider.isStreamLoading) {
                            Fluttertoast.showToast(
                                msg: 'Please wait'.tr,
                                gravity: ToastGravity.CENTER);
                            return;
                          }
                          this.shareTap();
                        },
                      ),
                      SizedBox(
                        width: 10.w,
                      ),
                      GestureDetector(
                        child: Container(
                          width: 20.w,
                          height: 20.w,
                          padding: EdgeInsets.all(1.w),
                          child: Image.asset(
                            "assets/images/chat/chat_detail_report.png",
                            width: 16.w,
                            color: themed.theme_c.iconColorMild, // 你想要的颜色
                            colorBlendMode: BlendMode.srcIn, // 混合模式
                          ),
                        ),
                        onTap: () {
                          ChatProvider chatProvider =
                              Provider.of<ChatProvider>(context, listen: false);
                          if (chatProvider.isStreamLoading) {
                            Fluttertoast.showToast(
                                msg: 'Please wait'.tr,
                                gravity: ToastGravity.CENTER);
                            return;
                          }
                          this.reportTap();
                        },
                      ),
                      // _item(onTap: this.likeTap),
                      // SizedBox(
                      //   width: 5.w,
                      // ),
                      // _item(isLike: false, onTap: this.unlikeTap),
                    ],
                  ),
                ),
              ],
            ),
          );
        });
  }
}

class PageIndicator extends StatelessWidget {
  final int current;
  final int total;
  final VoidCallback? onLeftTap;
  final VoidCallback? onNextTap;

  PageIndicator({
    required this.current,
    required this.total,
    this.onLeftTap,
    this.onNextTap,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        GestureDetector(
          onTap: current > 1 ? onLeftTap : null,
          child: Padding(
            padding: EdgeInsets.only(right: 2.0.w), // 调整左右边距
            child:
                // Icon(
                //   Icons.chevron_left,
                //   color: current == 1 ? Colors.grey[400] : Colors.grey[600],
                // ),
                Image.asset(
              current == 1
                  ? imagePath("chat", "chat_arrow_left_grey")
                  : imagePath("chat", "chat_arrow_left"),
              width: 20.w,
              color: themed.theme_c.iconColorMild, // 你想要的颜色
              colorBlendMode: BlendMode.srcIn, // 混合模式
            ),
          ),
        ),
        Text(
          '$current/$total',
          style: TextStyle(fontSize: 14.0, color: Colors.grey[600]),
        ),
        GestureDetector(
          onTap: current < total ? onNextTap : null,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 2.0.w), // 调整左右边距
            child: Image.asset(
              current == total
                  ? imagePath("chat", "chat_arrow_right_grey")
                  : imagePath("chat", "chat_arrow_right"),
              width: 20.w,
              color: themed.theme_c.iconColorMild, // 你想要的颜色
              colorBlendMode: BlendMode.srcIn, // 混合模式
            ),
          ),
        ),
        SizedBox(width: 4.0),
      ],
    );
  }
}
